module.exports = {
  LOGIN_USER : "LOGIN_USER",
  LOAD_PRODUCTS : "LOAD_PRODUCTS",
  CHANGE_QUANTITY_IN_CART : "CHANGE_QUANTITY_IN_CART",
  REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",
  SEARCH_PRODUCT_NAMES: "SEARCH_PRODUCT_NAMES"
};
